version: '3'
services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      #- "/Users/sabadam/BobdiUser/Tmp/MysqlDatad:/var/lib/mysql"
      - "/home/sabadam/BobdiUser/Tmp/MysqlDatad:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony
  php-fpm:
    build: ./php/
    command: "sh -c 'php-fpm -F -R  &>/n & symfony serve'"
    expose:
      - 8000
      - 9000
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - /home/sabadam/BobdiUser/Project/PhpWorkSpace/revolt:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_CONFIG:"client_host=host.docker.internal"
      - XDEBUG_SESSION:"PHPSTORM"
      #- XDEBUG_REMOTE_CONNECT_BACK:1
      #- XDEBUG_REMOTE_AUTOSTART:1
      - XDEBUG_MAXNESTING_LEVEL:1000
    networks:
      - symfony

  nginx-local:
    build:
      context: ./nginx
    ports:
      - 8080:80
    volumes:
      - /home/sabadam/BobdiUser/Project/PhpWorkSpace/revolt:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    networks:
      - symfony
    extra_hosts:
      - "host.docker.internal:host-gateway"
  adminer_php:
    image: dockette/adminer:mysql
    ports:
    - 8006:80
    depends_on:
      - db
      - php-fpm
    networks:
      - symfony
  inbucket:
    image: inbucket/inbucket
    container_name: inbucket
    restart: always
    ports:
      - "25:2500"
      - "9004:9000"
      - "1100:1100"
    networks:
      - symfony
networks:
  symfony: