version: '3.3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
    - 18000:8000
    - 10443:9443
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
volumes:
  portainer_data: